version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome
    volumes:
      - ./templates:/app/templates
    user: "1000:1000"  # Usa o mesmo UID/GID do usuário host